services:
  - type: web
    name: jaydus-ai-dashboard
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /health
