[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai", "@anthropic-ai/sdk"]
  # Set timeout for all functions
  included_files = ["**"]
  
[functions.openai-proxy]
  # Increase function timeout to 30 seconds to accommodate image generation
  timeout = 30

[functions.ai-proxy]
  # Increase function timeout to 30 seconds to accommodate image generation
  timeout = 30

[[edge_functions]]
  path = "/api/openai-stream"
  function = "openai-stream"

[[edge_functions]]
  path = "/api/ai-stream"
  function = "ai-stream"

[[headers]]
  for = "/*"
  [headers.values]
    Feature-Policy = "microphone 'self'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=self, geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co https://api.openai.com https://api.anthropic.com https://api.stability.ai https://*.stripe.com https://vitals.vercel-analytics.com; script-src 'self' https://*.stripe.com 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.pexels.com https://*.stripe.com https://images.unsplash.com https://*.supabase.co https://oaidalleapiprodscus.blob.core.windows.net; font-src 'self' https://fonts.gstatic.com; frame-src https://*.stripe.com; media-src 'self' data:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  VITE_ENABLE_MOCK_MODE = "false"